<?php
	$lang = 'en-US'; 
	$charset = 'utf-8'; 
	$org = '3AM Productions';
	$domain = '3AMProductions.net';
	$base_title = '3AM';
	$author = 'Gilbert J. Velasquez &amp; Jason R. Karns';
	$description = 'Dedicated to the latest Web Standards in Accessibility, Design and Programming using Client Server technology to maximize usability and profitability.';
	$keywords = 'xhtml,php,css,mysql,dom,javascript,ajax,db,database,rss,xml,html,standards,accessibility,usability,security,small business,open source,code,software,web applications,consulting,3am,productions,3am productions,web design,database-driven,dynamic';
	$category = 'Computers/Internet/Web_Design_and_Development/Designers/Full_Service';
	$title_separator =  ' // ';
?>
